name: Python commons CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      confirm_action:
        description: "Type 'yes' if you want to create a new tag"
        required: true
        default: "no"

jobs:
  build_package:
    uses: cyberrangecz/actions-templates/.github/workflows/python_build_template.yml@feat/add-python-code-quality-tools
    with:
      publish_and_tag: ${{ github.event.inputs.confirm_action }}
